### ISSUE TITLE
issue with local setup

### ISSUE THREAD

**Issue by RushiBhatt007** [WenjieDu/Time_Series_Database#1]
Hi, I am trying to use pypots, and one of the dependencies it uses is tsdb

Here's the issue I face when I import pypots on my local setup (I created a new environment and was able to download pypots with all dependencies successfully):

_ImportError: cannot import name 'load_specific_dataset' from 'tsdb' (c:\Users\RUSHI\anaconda3\envs\tf\lib\site-packages\tsdb\__init__.py)_

![image](https://user-images.githubusercontent.com/28632843/172027548-2bc7b060-13fd-41d2-bc59-bdee6fada793.png)

However, it works fine when I run the same thing on colab. 

The torch version is the only difference between my local (1.11.0+cpu) and colab (1.11.0+cu113). Could that be the potential issue?

**Comment by WenjieDu** [comment]
Hi there,<br><br>Thank you so much for your attention to TSDB! If you find TSDB helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice TSDB this useful tool. It matters and is definitely a kind of contribution.<br><br>I have received your message and will respond ASAP. Thank you for your patience! 😃<br><br>Best,<br>Wenjie

**Comment by WenjieDu** [comment]
Hi Rushi,

Thank you very much again for your feedback. This issue is caused by an API update. Since version `0.0.7`, function `load_specific_dataset` in TSDB is renamed to `load_dataset`, more straightforward and fewer characters. To solve this issue, please upgrade to the latest TSDB with `pip install tsdb --upgrade` or `pip install tsdb==0.0.7` to specify the version. Note that you should use the latest PyPOTS as well.

**Comment by RushiBhatt007** [comment]
Thank you Wenjie for the quick reply.

I used the latest version of both tsdb and pypots and it now works fine. Thank you once again!

**Comment by WenjieDu** [comment]
Absolutely my pleasure! Thank you very much for your support to project PyPOTS. 😃
